/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as AuthenticatedVolumesIndexRouteImport } from './routes/_authenticated/volumes/index'
import { Route as AuthenticatedVectorStoresIndexRouteImport } from './routes/_authenticated/vector-stores/index'
import { Route as AuthenticatedUsageIndexRouteImport } from './routes/_authenticated/usage/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSecretsIndexRouteImport } from './routes/_authenticated/secrets/index'
import { Route as AuthenticatedSandboxTemplatesIndexRouteImport } from './routes/_authenticated/sandbox-templates/index'
import { Route as AuthenticatedRegistryIndexRouteImport } from './routes/_authenticated/registry/index'
import { Route as AuthenticatedObservabilityIndexRouteImport } from './routes/_authenticated/observability/index'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated/objects/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedK8sClustersIndexRouteImport } from './routes/_authenticated/k8s-clusters/index'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated/instances/index'
import { Route as AuthenticatedGpuInventoryIndexRouteImport } from './routes/_authenticated/gpu-inventory/index'
import { Route as AuthenticatedFilesystemsIndexRouteImport } from './routes/_authenticated/filesystems/index'
import { Route as AuthenticatedEncryptionIndexRouteImport } from './routes/_authenticated/encryption/index'
import { Route as AuthenticatedBareMetalIndexRouteImport } from './routes/_authenticated/bare-metal/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedVolumesVolumeIdRouteImport } from './routes/_authenticated/volumes/$volumeId'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSecretsSecretIdRouteImport } from './routes/_authenticated/secrets/$secretId'
import { Route as AuthenticatedInstancesInstanceIdRouteImport } from './routes/_authenticated/instances/$instanceId'
import { Route as AuthenticatedInstanceOperationsOperationIdRouteImport } from './routes/_authenticated/instance-operations/$operationId'
import { Route as AuthenticatedFilesystemsFilesystemIdRouteImport } from './routes/_authenticated/filesystems/$filesystemId'
import { Route as AuthenticatedNetworksVpcsIndexRouteImport } from './routes/_authenticated/networks/vpcs/index'
import { Route as AuthenticatedNetworksSubnetsIndexRouteImport } from './routes/_authenticated/networks/subnets/index'
import { Route as AuthenticatedNetworksSecurityGroupsIndexRouteImport } from './routes/_authenticated/networks/security-groups/index'
import { Route as AuthenticatedNetworksRoutesIndexRouteImport } from './routes/_authenticated/networks/routes/index'
import { Route as AuthenticatedNetworksLoadBalancersIndexRouteImport } from './routes/_authenticated/networks/load-balancers/index'
import { Route as AuthenticatedInstancesInstanceIdOperationsRouteImport } from './routes/_authenticated/instances/$instanceId.operations'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedVolumesIndexRoute =
  AuthenticatedVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVectorStoresIndexRoute =
  AuthenticatedVectorStoresIndexRouteImport.update({
    id: '/vector-stores/',
    path: '/vector-stores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsageIndexRoute = AuthenticatedUsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecretsIndexRoute =
  AuthenticatedSecretsIndexRouteImport.update({
    id: '/secrets/',
    path: '/secrets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxTemplatesIndexRoute =
  AuthenticatedSandboxTemplatesIndexRouteImport.update({
    id: '/sandbox-templates/',
    path: '/sandbox-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryIndexRoute =
  AuthenticatedRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObservabilityIndexRoute =
  AuthenticatedObservabilityIndexRouteImport.update({
    id: '/observability/',
    path: '/observability/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedK8sClustersIndexRoute =
  AuthenticatedK8sClustersIndexRouteImport.update({
    id: '/k8s-clusters/',
    path: '/k8s-clusters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGpuInventoryIndexRoute =
  AuthenticatedGpuInventoryIndexRouteImport.update({
    id: '/gpu-inventory/',
    path: '/gpu-inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsIndexRoute =
  AuthenticatedFilesystemsIndexRouteImport.update({
    id: '/filesystems/',
    path: '/filesystems/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncryptionIndexRoute =
  AuthenticatedEncryptionIndexRouteImport.update({
    id: '/encryption/',
    path: '/encryption/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBareMetalIndexRoute =
  AuthenticatedBareMetalIndexRouteImport.update({
    id: '/bare-metal/',
    path: '/bare-metal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVolumesVolumeIdRoute =
  AuthenticatedVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecretsSecretIdRoute =
  AuthenticatedSecretsSecretIdRouteImport.update({
    id: '/secrets/$secretId',
    path: '/secrets/$secretId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesInstanceIdRoute =
  AuthenticatedInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstanceOperationsOperationIdRoute =
  AuthenticatedInstanceOperationsOperationIdRouteImport.update({
    id: '/instance-operations/$operationId',
    path: '/instance-operations/$operationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesystemsFilesystemIdRoute =
  AuthenticatedFilesystemsFilesystemIdRouteImport.update({
    id: '/filesystems/$filesystemId',
    path: '/filesystems/$filesystemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksVpcsIndexRoute =
  AuthenticatedNetworksVpcsIndexRouteImport.update({
    id: '/networks/vpcs/',
    path: '/networks/vpcs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSubnetsIndexRoute =
  AuthenticatedNetworksSubnetsIndexRouteImport.update({
    id: '/networks/subnets/',
    path: '/networks/subnets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksSecurityGroupsIndexRoute =
  AuthenticatedNetworksSecurityGroupsIndexRouteImport.update({
    id: '/networks/security-groups/',
    path: '/networks/security-groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksRoutesIndexRoute =
  AuthenticatedNetworksRoutesIndexRouteImport.update({
    id: '/networks/routes/',
    path: '/networks/routes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworksLoadBalancersIndexRoute =
  AuthenticatedNetworksLoadBalancersIndexRouteImport.update({
    id: '/networks/load-balancers/',
    path: '/networks/load-balancers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesInstanceIdOperationsRoute =
  AuthenticatedInstancesInstanceIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedInstancesInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/login/': typeof LoginIndexRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/bare-metal/': typeof AuthenticatedBareMetalIndexRoute
  '/encryption/': typeof AuthenticatedEncryptionIndexRoute
  '/filesystems/': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-inventory/': typeof AuthenticatedGpuInventoryIndexRoute
  '/instances/': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters/': typeof AuthenticatedK8sClustersIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/objects/': typeof AuthenticatedObjectsIndexRoute
  '/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/registry/': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates/': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/usage/': typeof AuthenticatedUsageIndexRoute
  '/vector-stores/': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes/': typeof AuthenticatedVolumesIndexRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/networks/load-balancers/': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes/': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups/': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets/': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs/': typeof AuthenticatedNetworksVpcsIndexRoute
}
export interface FileRoutesByTo {
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/bare-metal': typeof AuthenticatedBareMetalIndexRoute
  '/encryption': typeof AuthenticatedEncryptionIndexRoute
  '/filesystems': typeof AuthenticatedFilesystemsIndexRoute
  '/gpu-inventory': typeof AuthenticatedGpuInventoryIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/k8s-clusters': typeof AuthenticatedK8sClustersIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/sandbox-templates': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/secrets': typeof AuthenticatedSecretsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/usage': typeof AuthenticatedUsageIndexRoute
  '/vector-stores': typeof AuthenticatedVectorStoresIndexRoute
  '/volumes': typeof AuthenticatedVolumesIndexRoute
  '/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/networks/load-balancers': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/networks/routes': typeof AuthenticatedNetworksRoutesIndexRoute
  '/networks/security-groups': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/networks/subnets': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/networks/vpcs': typeof AuthenticatedNetworksVpcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/filesystems/$filesystemId': typeof AuthenticatedFilesystemsFilesystemIdRoute
  '/_authenticated/instance-operations/$operationId': typeof AuthenticatedInstanceOperationsOperationIdRoute
  '/_authenticated/instances/$instanceId': typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  '/_authenticated/secrets/$secretId': typeof AuthenticatedSecretsSecretIdRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/volumes/$volumeId': typeof AuthenticatedVolumesVolumeIdRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/bare-metal/': typeof AuthenticatedBareMetalIndexRoute
  '/_authenticated/encryption/': typeof AuthenticatedEncryptionIndexRoute
  '/_authenticated/filesystems/': typeof AuthenticatedFilesystemsIndexRoute
  '/_authenticated/gpu-inventory/': typeof AuthenticatedGpuInventoryIndexRoute
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
  '/_authenticated/k8s-clusters/': typeof AuthenticatedK8sClustersIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/_authenticated/registry/': typeof AuthenticatedRegistryIndexRoute
  '/_authenticated/sandbox-templates/': typeof AuthenticatedSandboxTemplatesIndexRoute
  '/_authenticated/secrets/': typeof AuthenticatedSecretsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/usage/': typeof AuthenticatedUsageIndexRoute
  '/_authenticated/vector-stores/': typeof AuthenticatedVectorStoresIndexRoute
  '/_authenticated/volumes/': typeof AuthenticatedVolumesIndexRoute
  '/_authenticated/instances/$instanceId/operations': typeof AuthenticatedInstancesInstanceIdOperationsRoute
  '/_authenticated/networks/load-balancers/': typeof AuthenticatedNetworksLoadBalancersIndexRoute
  '/_authenticated/networks/routes/': typeof AuthenticatedNetworksRoutesIndexRoute
  '/_authenticated/networks/security-groups/': typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  '/_authenticated/networks/subnets/': typeof AuthenticatedNetworksSubnetsIndexRoute
  '/_authenticated/networks/vpcs/': typeof AuthenticatedNetworksVpcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login/callback'
    | '/login/'
    | '/filesystems/$filesystemId'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/secrets/$secretId'
    | '/settings/api-keys'
    | '/volumes/$volumeId'
    | '/audit/'
    | '/bare-metal/'
    | '/encryption/'
    | '/filesystems/'
    | '/gpu-inventory/'
    | '/instances/'
    | '/k8s-clusters/'
    | '/notifications/'
    | '/objects/'
    | '/observability/'
    | '/registry/'
    | '/sandbox-templates/'
    | '/secrets/'
    | '/settings/'
    | '/usage/'
    | '/vector-stores/'
    | '/volumes/'
    | '/instances/$instanceId/operations'
    | '/networks/load-balancers/'
    | '/networks/routes/'
    | '/networks/security-groups/'
    | '/networks/subnets/'
    | '/networks/vpcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/callback'
    | '/'
    | '/login'
    | '/filesystems/$filesystemId'
    | '/instance-operations/$operationId'
    | '/instances/$instanceId'
    | '/secrets/$secretId'
    | '/settings/api-keys'
    | '/volumes/$volumeId'
    | '/audit'
    | '/bare-metal'
    | '/encryption'
    | '/filesystems'
    | '/gpu-inventory'
    | '/instances'
    | '/k8s-clusters'
    | '/notifications'
    | '/objects'
    | '/observability'
    | '/registry'
    | '/sandbox-templates'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/vector-stores'
    | '/volumes'
    | '/instances/$instanceId/operations'
    | '/networks/load-balancers'
    | '/networks/routes'
    | '/networks/security-groups'
    | '/networks/subnets'
    | '/networks/vpcs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/login/callback'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/filesystems/$filesystemId'
    | '/_authenticated/instance-operations/$operationId'
    | '/_authenticated/instances/$instanceId'
    | '/_authenticated/secrets/$secretId'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/volumes/$volumeId'
    | '/_authenticated/audit/'
    | '/_authenticated/bare-metal/'
    | '/_authenticated/encryption/'
    | '/_authenticated/filesystems/'
    | '/_authenticated/gpu-inventory/'
    | '/_authenticated/instances/'
    | '/_authenticated/k8s-clusters/'
    | '/_authenticated/notifications/'
    | '/_authenticated/objects/'
    | '/_authenticated/observability/'
    | '/_authenticated/registry/'
    | '/_authenticated/sandbox-templates/'
    | '/_authenticated/secrets/'
    | '/_authenticated/settings/'
    | '/_authenticated/usage/'
    | '/_authenticated/vector-stores/'
    | '/_authenticated/volumes/'
    | '/_authenticated/instances/$instanceId/operations'
    | '/_authenticated/networks/load-balancers/'
    | '/_authenticated/networks/routes/'
    | '/_authenticated/networks/security-groups/'
    | '/_authenticated/networks/subnets/'
    | '/_authenticated/networks/vpcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/volumes/': {
      id: '/_authenticated/volumes/'
      path: '/volumes'
      fullPath: '/volumes/'
      preLoaderRoute: typeof AuthenticatedVolumesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vector-stores/': {
      id: '/_authenticated/vector-stores/'
      path: '/vector-stores'
      fullPath: '/vector-stores/'
      preLoaderRoute: typeof AuthenticatedVectorStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage/': {
      id: '/_authenticated/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof AuthenticatedUsageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets/': {
      id: '/_authenticated/secrets/'
      path: '/secrets'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AuthenticatedSecretsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandbox-templates/': {
      id: '/_authenticated/sandbox-templates/'
      path: '/sandbox-templates'
      fullPath: '/sandbox-templates/'
      preLoaderRoute: typeof AuthenticatedSandboxTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/': {
      id: '/_authenticated/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof AuthenticatedRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observability/': {
      id: '/_authenticated/observability/'
      path: '/observability'
      fullPath: '/observability/'
      preLoaderRoute: typeof AuthenticatedObservabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/k8s-clusters/': {
      id: '/_authenticated/k8s-clusters/'
      path: '/k8s-clusters'
      fullPath: '/k8s-clusters/'
      preLoaderRoute: typeof AuthenticatedK8sClustersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpu-inventory/': {
      id: '/_authenticated/gpu-inventory/'
      path: '/gpu-inventory'
      fullPath: '/gpu-inventory/'
      preLoaderRoute: typeof AuthenticatedGpuInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/': {
      id: '/_authenticated/filesystems/'
      path: '/filesystems'
      fullPath: '/filesystems/'
      preLoaderRoute: typeof AuthenticatedFilesystemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encryption/': {
      id: '/_authenticated/encryption/'
      path: '/encryption'
      fullPath: '/encryption/'
      preLoaderRoute: typeof AuthenticatedEncryptionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bare-metal/': {
      id: '/_authenticated/bare-metal/'
      path: '/bare-metal'
      fullPath: '/bare-metal/'
      preLoaderRoute: typeof AuthenticatedBareMetalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volumes/$volumeId': {
      id: '/_authenticated/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof AuthenticatedVolumesVolumeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets/$secretId': {
      id: '/_authenticated/secrets/$secretId'
      path: '/secrets/$secretId'
      fullPath: '/secrets/$secretId'
      preLoaderRoute: typeof AuthenticatedSecretsSecretIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$instanceId': {
      id: '/_authenticated/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instance-operations/$operationId': {
      id: '/_authenticated/instance-operations/$operationId'
      path: '/instance-operations/$operationId'
      fullPath: '/instance-operations/$operationId'
      preLoaderRoute: typeof AuthenticatedInstanceOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filesystems/$filesystemId': {
      id: '/_authenticated/filesystems/$filesystemId'
      path: '/filesystems/$filesystemId'
      fullPath: '/filesystems/$filesystemId'
      preLoaderRoute: typeof AuthenticatedFilesystemsFilesystemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/vpcs/': {
      id: '/_authenticated/networks/vpcs/'
      path: '/networks/vpcs'
      fullPath: '/networks/vpcs/'
      preLoaderRoute: typeof AuthenticatedNetworksVpcsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/subnets/': {
      id: '/_authenticated/networks/subnets/'
      path: '/networks/subnets'
      fullPath: '/networks/subnets/'
      preLoaderRoute: typeof AuthenticatedNetworksSubnetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/security-groups/': {
      id: '/_authenticated/networks/security-groups/'
      path: '/networks/security-groups'
      fullPath: '/networks/security-groups/'
      preLoaderRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/routes/': {
      id: '/_authenticated/networks/routes/'
      path: '/networks/routes'
      fullPath: '/networks/routes/'
      preLoaderRoute: typeof AuthenticatedNetworksRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/networks/load-balancers/': {
      id: '/_authenticated/networks/load-balancers/'
      path: '/networks/load-balancers'
      fullPath: '/networks/load-balancers/'
      preLoaderRoute: typeof AuthenticatedNetworksLoadBalancersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$instanceId/operations': {
      id: '/_authenticated/instances/$instanceId/operations'
      path: '/operations'
      fullPath: '/instances/$instanceId/operations'
      preLoaderRoute: typeof AuthenticatedInstancesInstanceIdOperationsRouteImport
      parentRoute: typeof AuthenticatedInstancesInstanceIdRoute
    }
  }
}

interface AuthenticatedInstancesInstanceIdRouteChildren {
  AuthenticatedInstancesInstanceIdOperationsRoute: typeof AuthenticatedInstancesInstanceIdOperationsRoute
}

const AuthenticatedInstancesInstanceIdRouteChildren: AuthenticatedInstancesInstanceIdRouteChildren =
  {
    AuthenticatedInstancesInstanceIdOperationsRoute:
      AuthenticatedInstancesInstanceIdOperationsRoute,
  }

const AuthenticatedInstancesInstanceIdRouteWithChildren =
  AuthenticatedInstancesInstanceIdRoute._addFileChildren(
    AuthenticatedInstancesInstanceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFilesystemsFilesystemIdRoute: typeof AuthenticatedFilesystemsFilesystemIdRoute
  AuthenticatedInstanceOperationsOperationIdRoute: typeof AuthenticatedInstanceOperationsOperationIdRoute
  AuthenticatedInstancesInstanceIdRoute: typeof AuthenticatedInstancesInstanceIdRouteWithChildren
  AuthenticatedSecretsSecretIdRoute: typeof AuthenticatedSecretsSecretIdRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedVolumesVolumeIdRoute: typeof AuthenticatedVolumesVolumeIdRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedBareMetalIndexRoute: typeof AuthenticatedBareMetalIndexRoute
  AuthenticatedEncryptionIndexRoute: typeof AuthenticatedEncryptionIndexRoute
  AuthenticatedFilesystemsIndexRoute: typeof AuthenticatedFilesystemsIndexRoute
  AuthenticatedGpuInventoryIndexRoute: typeof AuthenticatedGpuInventoryIndexRoute
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
  AuthenticatedK8sClustersIndexRoute: typeof AuthenticatedK8sClustersIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedObservabilityIndexRoute: typeof AuthenticatedObservabilityIndexRoute
  AuthenticatedRegistryIndexRoute: typeof AuthenticatedRegistryIndexRoute
  AuthenticatedSandboxTemplatesIndexRoute: typeof AuthenticatedSandboxTemplatesIndexRoute
  AuthenticatedSecretsIndexRoute: typeof AuthenticatedSecretsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedUsageIndexRoute: typeof AuthenticatedUsageIndexRoute
  AuthenticatedVectorStoresIndexRoute: typeof AuthenticatedVectorStoresIndexRoute
  AuthenticatedVolumesIndexRoute: typeof AuthenticatedVolumesIndexRoute
  AuthenticatedNetworksLoadBalancersIndexRoute: typeof AuthenticatedNetworksLoadBalancersIndexRoute
  AuthenticatedNetworksRoutesIndexRoute: typeof AuthenticatedNetworksRoutesIndexRoute
  AuthenticatedNetworksSecurityGroupsIndexRoute: typeof AuthenticatedNetworksSecurityGroupsIndexRoute
  AuthenticatedNetworksSubnetsIndexRoute: typeof AuthenticatedNetworksSubnetsIndexRoute
  AuthenticatedNetworksVpcsIndexRoute: typeof AuthenticatedNetworksVpcsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFilesystemsFilesystemIdRoute:
    AuthenticatedFilesystemsFilesystemIdRoute,
  AuthenticatedInstanceOperationsOperationIdRoute:
    AuthenticatedInstanceOperationsOperationIdRoute,
  AuthenticatedInstancesInstanceIdRoute:
    AuthenticatedInstancesInstanceIdRouteWithChildren,
  AuthenticatedSecretsSecretIdRoute: AuthenticatedSecretsSecretIdRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedVolumesVolumeIdRoute: AuthenticatedVolumesVolumeIdRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBareMetalIndexRoute: AuthenticatedBareMetalIndexRoute,
  AuthenticatedEncryptionIndexRoute: AuthenticatedEncryptionIndexRoute,
  AuthenticatedFilesystemsIndexRoute: AuthenticatedFilesystemsIndexRoute,
  AuthenticatedGpuInventoryIndexRoute: AuthenticatedGpuInventoryIndexRoute,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
  AuthenticatedK8sClustersIndexRoute: AuthenticatedK8sClustersIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedObservabilityIndexRoute: AuthenticatedObservabilityIndexRoute,
  AuthenticatedRegistryIndexRoute: AuthenticatedRegistryIndexRoute,
  AuthenticatedSandboxTemplatesIndexRoute:
    AuthenticatedSandboxTemplatesIndexRoute,
  AuthenticatedSecretsIndexRoute: AuthenticatedSecretsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedUsageIndexRoute: AuthenticatedUsageIndexRoute,
  AuthenticatedVectorStoresIndexRoute: AuthenticatedVectorStoresIndexRoute,
  AuthenticatedVolumesIndexRoute: AuthenticatedVolumesIndexRoute,
  AuthenticatedNetworksLoadBalancersIndexRoute:
    AuthenticatedNetworksLoadBalancersIndexRoute,
  AuthenticatedNetworksRoutesIndexRoute: AuthenticatedNetworksRoutesIndexRoute,
  AuthenticatedNetworksSecurityGroupsIndexRoute:
    AuthenticatedNetworksSecurityGroupsIndexRoute,
  AuthenticatedNetworksSubnetsIndexRoute:
    AuthenticatedNetworksSubnetsIndexRoute,
  AuthenticatedNetworksVpcsIndexRoute: AuthenticatedNetworksVpcsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
